/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.Connection;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import java.util.regex.Pattern;
import java.security.MessageDigest;
import java.util.prefs.Preferences;


/**
 *
 * @author User
 */
public class f_login extends javax.swing.JFrame {
    
    Connection conn = koneksi.connect();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(f_login.class.getName());
    
    public String hashPassword(String password) {
            try {
                java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
                byte[] hash = md.digest(password.getBytes());

                StringBuilder hex = new StringBuilder();
                for (byte b : hash) {
                    String h = Integer.toHexString(0xff & b);
                    if (h.length() == 1) hex.append('0');
                    hex.append(h);
                }
                return hex.toString();

            } catch (Exception e) {
                return null;
            }
        }

    public f_login() {
        initComponents();
        setResizable(false);
        setTitle("");

        Preferences pref = Preferences.userRoot().node("login");

        String savedName = pref.get("nama", "");
        String savedPass = pref.get("password", "");

        username.setText(savedName);
        password.setText(savedPass);

        if (!savedName.isEmpty()) {
            remember_me.setSelected(true);
        }

        ImageIcon icon = new ImageIcon("E:\\NetBeansProjects\\Kos_TA\\src\\images\\login.png");

        int width = icon.getIconWidth();
        int height = icon.getIconHeight();

        Image image = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(image);

        javax.swing.JLabel background = new javax.swing.JLabel();
        background.setIcon(resizedIcon);
        background.setBounds(0, 0, width, height);

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));

        setSize(width, height);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        username = new javax.swing.JTextField();
        remember_me = new javax.swing.JCheckBox();
        login_button = new javax.swing.JButton();
        sign_up = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        textField1.setText("textField1");

        jLabel1.setText("jLabel1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(this::usernameActionPerformed);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 194, 166, 32));

        remember_me.addActionListener(this::remember_meActionPerformed);
        getContentPane().add(remember_me, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 290, 20, 20));

        login_button.setBackground(new java.awt.Color(25, 104, 226));
        login_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("LOGIN");
        login_button.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_buttonFocusGained(evt);
            }
        });
        login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_buttonMouseExited(evt);
            }
        });
        login_button.addActionListener(this::login_buttonActionPerformed);
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 320, 280, 44));

        sign_up.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sign_up.setForeground(new java.awt.Color(25, 104, 226));
        sign_up.setText("Sign Up");
        sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sign_upMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sign_upMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sign_upMouseExited(evt);
            }
        });
        getContentPane().add(sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 380, -1, -1));

        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 240, 166, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowActivated

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void login_buttonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_buttonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonFocusGained

    private void login_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseEntered
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_button.setToolTipText("Klik untuk login");
        login_button.setBackground(new Color(30, 100, 210));
    }//GEN-LAST:event_login_buttonMouseEntered

    private void login_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_buttonMouseExited
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_login_buttonMouseExited

    private void sign_upMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upMouseEntered
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sign_upMouseEntered

    private void sign_upMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upMouseExited
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_sign_upMouseExited

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained

    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost

    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained

    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

    }//GEN-LAST:event_passwordFocusLost

    private void remember_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remember_meActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remember_meActionPerformed

    private void sign_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sign_upMouseClicked
        new f_sign_up().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sign_upMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username_baru = username.getText();
        String password_baru = new String(password.getPassword());

        // hash password
        String hashedPassword = hashPassword(password_baru);

        try {
            Connection conn = koneksi.connect();

            String sql = "SELECT * FROM user WHERE nama=? AND password=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, username_baru);
            pst.setString(2, hashedPassword);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                
                // session
                session.username = rs.getString("nama");
                session.email = rs.getString("email");
                session.id_user = rs.getInt("id_user");
                session.foto = rs.getString("foto_profil");
                session.role = rs.getString("role");

                // remember me
                Preferences pref = Preferences.userRoot().node("login");

                if (remember_me.isSelected()) {
                    pref.put("nama", username_baru);
                    pref.put("password", password_baru);
                } else {
                    pref.remove("nama");
                    pref.remove("password");
                }

                JOptionPane.showMessageDialog(this, "Login berhasil!");

                if (session.role.equals("pemilik_kos")) {
                    new p_dashboard_pemilik().setVisible(true);
                    this.dispose();
                } else {
                    new home_user().setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Password atau username salah!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new f_login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox remember_me;
    private javax.swing.JLabel sign_up;
    private java.awt.TextField textField1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
